name: Secure DevSecOps Pipeline 

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 

jobs: 
  build_and_package: 
    name: BUILD-JOB 
    runs-on: self-hosted 

    permissions: 
      actions: read 
      contents: read 
      security-events: write # Required to upload findings to the Security tab 

    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4 
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: BUILD 
        run: npm install 

      - name: TEST 
        run: echo "code is tested!" 

      - name: Artifact upload 
        uses: actions/upload-artifact@v7 
        with: 
          name: artifact-1 
          path: | 
            package* 
          retention-days: 7

 

 
